[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# NOTE: You must set these environment variables in Netlify dashboard:
# NEXT_PUBLIC_SUPABASE_URL = https://your-project-ref.supabase.co
# SUPABASE_ANON_KEY = your-anon-key-starting-with-eyJ
# SUPABASE_SERVICE_ROLE_KEY = your-service-role-key-starting-with-eyJ
# JWT_SECRET = your-secure-jwt-secret