[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"

# Force fresh builds to prevent Prisma cache issues
[build.processing]
  skip_processing = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables for Prisma
[context.production.environment]
  PRISMA_GENERATE_DATAPROXY = "false"

# NOTE: You must set DATABASE_URL environment variable in Netlify dashboard
# For PostgreSQL: postgresql://username:password@host:port/database?sslmode=require
# For testing with SQLite (will have limitations): file:./dev.db